### ISSUE TITLE
Make post synchronizing more flexible

### ISSUE THREAD

**Issue by s7nkuridza** [inpsyde/MultilingualPress#105]
Currently coping post does function `Mlp_Translatable_Post_Data::save()`, called with wordpress hook. I'm working on another plugin for batch coping woocommerce products(custom posts) and I't would be helpful if MLP save function could be called globally. Then only MLP would in charge of coping posts.

**Comment by kraftner** [comment]
I think this relates to #117 and #125.

**Comment by Dinamiko** [comment]
New features will be added in new version 3, we are going to provide support only for bugs in version 2.
