### ISSUE TITLE
Allow cross-site media insertion

### ISSUE THREAD

**Issue by Biont** [inpsyde/MultilingualPress#139]
This is a feature that would not only be a neat addition to our feature set, but also has the potential to answer all demands for a global media library (which is something we probably cannot do) by providing a somewhat elegant workaround. (Keeping all "global" files in one blog and referencing it with this feature)

The idea is to offer a way to add attachments from remote blogs when editing a post. The implementation could be like this:
## MLP Attachment Shortcode

The first step would be to provide a shortcode that switches to the target blog, fetches and renders an attachment, and then switches back. The shortcode wraps around the output that WP would normally produce when an image is inserted (including all shortcodes related to it).

From the top of my head, it could look like this:
`"[mlp-attachment blog_id="1"]$actual_attachment_shortcode[/mlp-attachment]"`

It would simply `switch_to_blog()`, then `do_shortcode( $content )` and then switch back. It should also keep TinyMCE support in place (we might need to add code that hides our shortcode)
## Extend the media modal

This will probably prove to be a tough one. The WP Media Modal would need to be extended to support switching between blogs. For example: 
- Add a tab row/dropdown/toggle group that refreshes the image library whenever it is changed so that the main view shows images of the selected site
- If a remote site is selected, the "Insert into post" callback needs to be replaced with a solution that it inserts the shortcode described above.
## Handle "copy source post"

To make this feature work with this function we would either need to
- add the shortcode for _all new_ attachments (and let the callback switch only if needed). Solve the issue by sidestepping it.

or 
-  Search & Replace the post content on every update. Probably the path to insanity

Sadly, this implies that the **elegant** way to make the post content "portable" would be to make a pretty bold change: Wrap every new attachment with our shortcode, regardless of an actual intention to make a cross-site insert. Some other opinions on this would be appreciated.
### Bonus: Hook into #140 (Process source post data) & #141 (Shortcode API)

With these features in place, the problem described above could be solved as well, offering a way to let the user to choose what to keep.
### Bonus: Allow transferring attachments

Should we choose to go through with #140 and #141, why not ask the user whether to reference the source blog's attachment or import it to the target site? Code for copying attachments exists (probably needs a separate issue), we just need to discuss if this is something we want

**Comment by Dinamiko** [comment]
New features will be added to new version 3, we are going to provide support only for bugs in version 2.
