### ISSUE TITLE
Add a shortcode translation API

### ISSUE THREAD

**Issue by Biont** [inpsyde/MultilingualPress#141]
This issue depends on #140 to be implemented

A Shortcode Translation API could allow all parameters of any shortcode to be changed according to the current blog context, or instead allow removing the shortcode entirely (returning just its content, if available). Code for this is already written. We simply need to decide if we want to use it.

It works by copying the WP core shortcode API but replace its callbacks with a custom filter that passes an object containg all shortcode data along with a method to print out a new shortcode. There just needs to be a way to run it when the user copies a post. This is why I mentioned #140 as a requirement

It allows external code to register translation handlers for a specific shortcode tag. The handler receives the shortcode data along with source and target blog ID.

**Comment by Dinamiko** [comment]
New features will be added in new version 3, we are going to provide support only for bugs in version 2.
