### ISSUE TITLE
Provide a hook after post sync has finished

### ISSUE THREAD

**Issue by Biont** [inpsyde/MultilingualPress#144]
We currently provide the `mlp_pre_save_post` filter to allow changing the post data before it is saved to the database.

Sadly, we do not provide a `mlp_after_save_post` (or similar) hook once the post has been saved. This means that there is no way to get hold of all relevant data **including the remote post ID** using the MLP API. You cannot rely on the existance of the remote post ID since the current save action might be the first time a post is saved, so the remote posts do not exist yet.

This is critical for anyone trying to do stuff like syncing attachments or any other post data that relies on a post ID. So it would be a good idea to add such a hook in the future.
#### Places to add the hook:

Probably [here](https://github.com/inpsyde/multilingual-press/blob/master/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L170) and [here](https://github.com/inpsyde/multilingual-press/blob/master/inc/post-translator/Mlp_Translatable_Post_Data.php#L223)
### Alternative:

Enhance the `$save_context` so that it contains more useful data when it is passed into `mlp_after_post_synchronization`

**Comment by tfrommen** [comment]
This has been [implemented for v3](https://github.com/inpsyde/MultilingualPress/blob/8b40b35073299494fb1a974cba12c5d937a9ea19/src/Translation/Post/MetaBox/TranslationMetadataUpdater.php#L171-L191).
