### ISSUE TITLE
Improve Dashboard Widget

### ISSUE THREAD

**Issue by tfrommen** [inpsyde/MultilingualPress#190]
The _Untranslated Posts_ dashboard widget needs to be refactored as there are several things not quite right.
- [x] List only sites the current user can access.
- [x] Add a widget controller (i.e., `control_callback`) to choose between displaying only the current site's posts or all site's posts.
- [x] List only (remote) posts the current user can edit.
- [x] Do not list posts with a specific post status (for example, `auto-draft` and `trash`, although this should be a filterable post status array).
- [x] Indicate the (custom) post type.
- [x] Display an appropriate message if there are no related sites.
- [x] Display an appropriate message if there are no untranslated posts.
- [x] Don't display custom post types if they are not activated as translatable in MultilingualPress settings page see [Forum ](https://wordpress.org/support/topic/custom-post-type-in-dashboard-widget?replies=3#post-8007468)
- [x] Do not display UI in the _Publish_ meta box for not activated post types.
- [x] Do not update the setting data for not activated post types.

**Comment by konus1** [comment]
- [ ] Don't display custom post types if they are not activated as transable in in MultilingualPress settings page see [Forum ](https://wordpress.org/support/topic/custom-post-type-in-dashboard-widget?replies=3#post-8007468)

**Comment by tfrommen** [comment]
Fixed vor v3.
