### ISSUE TITLE
Translate CPT permalinks

### ISSUE THREAD

**Issue by hatsumatsu** [inpsyde/MultilingualPress#192]
Multilingualpress seems to have problems with translated custom post type permalinks. 
When registering a custom post types like this, Multilingualpress' navigation links on CPT archive and single views still use the untranslated slug:

```
register_post_type( 
    'projects', 
    array( 
        'rewrite' => array( 
            'slug' => __( 'projects', 'your-text-domain' ) // makes permalink translatable via PO files...
        ),
        'has_archive' => __( 'projects', 'your-text-domain' ), // makes permalink translatable via PO files...
 );
```

**Comment by tfrommen** [comment]
MultilingualPress doesn't use the _untranslated_ slug, it uses the *current* translation with respect to the current site. There are some hard-coded solutions to account for translated CPT archive links, such as [this WordPress.org support topic](https://wordpress.org/support/topic/translate-cpt-slugs?replies=8), however, this is not a general solution.

We have this on our list, although it doesn't have a high priority right now.

**Comment by hatsumatsu** [comment]
Thanks for your insights. Unfortunately the workaround mentioned in the WP.org topic feels quite "hacky", using `str_replace`, especially if you have a ot of CPTs and custom taxonomies. 

Are there different slutions to achieve translated CPT permalinks you can recommend?

Would be great to see this fixed in future versions, great plugin anyway!

**Comment by tfrommen** [comment]
Yes, the _solution_ in the linked support topic is definitely only a workaround, and quite hacky&mdash;and not (easily) applicable to the _general_ case.

The problem here is that you basically have to load all your translatable data in every language of your network. `switch_to_blog()` doesn't switch translations, because this is slow and performance-heavy.  
A pretty straight forward solution (although depending on a specific WordPress version and/or a third-party plugin) is to use the WordPress REST API. You already have the combination of site ID and post ID for your remote target. So all you have to do is _ask_ the remote site for the permalink of the specific post.

With the current state of the REST API (and its future regarding to core WordPress), however, this is also not a full-fledged solution.

Once again, we have this on our list, as you're, of course, not the first who asked this. ;)

**Comment by ArnaudBan** [comment]
👍 
I really need this to be fixed. I understand the complexity of the issue, but this is really important.

**Comment by ramsesz** [comment]
Is this issue resolved yet? Or any decent workaround available?

**Comment by Dinamiko** [comment]
This is already done in new MultilingualPress version 3. Regarding the release it will probably be during September 2018.

**Comment by s-a-s-k-i-a** [comment]
I am using multilingual press 3 and am still seeing an issue with translated custom post type slugs. getting 404 when using po file to translate and also when using the provided translation slug field under network website's multilingual tab.

**Comment by Dinamiko** [comment]
Hi @s-a-s-k-i-a, your configuration looks correct, can you please create a issue on MultilingualPress support? we can take a deeper look from there, thanks.

**Comment by s-a-s-k-i-a** [comment]
@Dinamiko 
thanks for your reply. I am currently already in a dialogue with inpsyde support. Will post here, if I know more.

**Comment by asadowski10** [comment]
@s-a-s-k-i-a I had the same problem, and it came from the language of my back office. indeed permalinks are generated by taking the language of the back office ...
I solved the problem by hardcoding the slug by recovering the language of the front office.

**Comment by s-a-s-k-i-a** [comment]
@asadowski10
Thanks for joining the discussion!
How do you mean?

The WP Lang for the german site is set to de_DE in WP admin settings.
The WP Lang for the english site is set to en_US

My user profile lang is set to de_DE no matter which network site I am currently in.

**Comment by asadowski10** [comment]
@s-a-s-k-i-a 
To work correctly, you must configure your back office language like that of the front office in order to generate the rewrites rules correctly.

Example:
English site (en_EN), your user account must have the language (en_EN) (https://monsite.com/english-slug/) because if your user account has the language (de_DE) it will try to generate a rewrite rule with the translation de_DE (https://monsite.com/dutch-slug/) and therefore you will have 404.

I solved my problem by "hardcoding" the slugs in my code during my register_post_type.

```php
$translated_slugs = [
	'fr_FR' => 'portraits',
	'en_GB' => 'testimonies',
	'es_ES' => 'testimonios',
];

$args = [			
	'rewrite'	=> [
		'slug' => $translated_slugs[ get_locale() ] ?? 'portraits',
	],
];

register_post_type( 'cpt', $args );
```

**Comment by s-a-s-k-i-a** [comment]
@asadowski10 
Thanks very much!
This fixed the issue for me as well!
Provided po/mo files weren't doing a thing.. I had to hardcode the slug rewrite like mentioned above.

**Comment by asadowski10** [comment]
@s-a-s-k-i-a I took a long time to find the problem despite the exchanges with the support ... and the official documentation does not show this problem.

**Comment by s-a-s-k-i-a** [comment]
@asadowski10 
Same here.
But support said they will improve their documentation.

I think issue here is not really multilingualpress but how wordpress itself handles permalink generation itself.

**Comment by s-a-s-k-i-a** [comment]
Today I set up a new network site for testing purposes in that very same network and I am now seeing the permalink issue again. No matter what I try, the permalinks are not being generated with my custom translations., instead the german slugs are being used in the english site with /en/ prefixed.
Above code is present in the installation, my user is set to target language, permalinks have been flushed several times.

There is something wrong here.

@Dinamiko

**Comment by gchtr** [comment]
I’ve stumbled over this problem as well. I solved it with a filter that automatically loads the post type slugs from the MultilingualPress options and updates the `rewrite` argument that is used when a custom post type is registered through `register_post_type()`.

This loads the options from the inputs in the **Post Type Slugs** tab in the website settings in the Network, as described in [How to translate custom post types and taxonomies](https://multilingualpress.org/docs/how-to-translate-custom-post-types-and-taxonomies/#Enter-Post-Type-slug-value-on-each-site).

```php
/**
 * Updates the rewrite => slug argument when registering a post type.
 *
 * Will use the option from the "Post Type Slugs" tab the Network Settings of a website, in case
 * it’s not empty.
 *
 * @see register_post_type()
 *
 * @param array  $args      An array of arguments that will be passed to register_post_type().
 * @param string $post_type The name/slug of the post type.
 *
 * @return array Updated arguments.
 */
add_filter( 'register_post_type_args', function( $args, $post_type ) {
    // Ignore built-in or non-public post types.
    if ( ( isset( $args['_builtin' ] ) && $args['_builtin'] )
        || ( isset( $args['public'] ) && ! $args['public'] )
    ) {
        return $args;
    }

    $slug_settings = get_network_option(
    	0,
	    \Inpsyde\MultilingualPress\Core\Admin\PostTypeSlugsSettingsRepository::OPTION,
	    []
    );
    $blog_id       = get_current_blog_id();

    if ( empty( $slug_settings[ $blog_id ][ $post_type ] ) ) {
        return $args;
    }

    $args = array_merge( $args, [
        'rewrite' => [
            'slug' => $slug_settings[ $blog_id ][ $post_type ]
        ],
    ] );

    return $args;
}, 11, 2 );
```

Make sure to flush permalinks after adding this filter.

@s-a-s-k-i-a This should give you a more automated solution.
