### ISSUE TITLE
Add en_NZ in the language table

### ISSUE THREAD

**Issue by bueltge** [inpsyde/MultilingualPress#217]
Add `en_NZ` as default param for the language table, visible in the language manager.

**Comment by tfrommen** [comment]
Has been added to `master` in 49d2d923324a0b3e4b490f110584ae430d7d99ff.

**Comment by GaryJones** [comment]
If it's in `master`, can this be closed?

**Comment by tfrommen** [comment]
Yep, @GaryJones, yep. :)
