### ISSUE TITLE
Bulk action for relating sites

### ISSUE THREAD

**Issue by tfrommen** [inpsyde/MultilingualPress#226]
It would be very handy to have some kind of bulk action in order to relate all (individually selected) sites.

**Comment by ahmed-sigmalux** [comment]
Any progress on this feature?

**Comment by tfrommen** [comment]
No, not yet. It doesn't have a high priority right now as we're still in the middle of a huge refactoring, and this is a new feature.

**Comment by Dinamiko** [comment]
This is already done in new MultilingualPress version 3. Regarding the release it will probably be during September 2018.
