### ISSUE TITLE
MLP cannot be properly activated by WP CLI

### ISSUE THREAD

**Issue by dimitrystd** [inpsyde/MultilingualPress#230]
#### Version Information
- WordPress: 4.6
- MultilingualPress: 2.4.4

I'm trying to automate sandbox installation and use WP CLI for this. And the problem that MLP is displayed as activated but there is no tables in DB.
#### Steps to Reproduce
1. Install WP
2. Install and activate MLP by WP CLI
   `
   sudo -E -u www-data wp --path=/var/www/html plugin install multilingual-press
   sudo -E -u www-data wp --path=/var/www/html plugin activate multilingual-press  --network
   `
3. Check MLP on Plugins page
   ![plugins network admin_ wordpress demo sites wordpress-000641](https://cloud.githubusercontent.com/assets/1511122/18089322/0bac7aa4-6ec8-11e6-8361-1c8496d7552f.png)  
   Looks good
#### What I Expected

I should be able to insert some data right in appropriate tables. Or configure sites manually.
As workaround i can `Network deactivate` and then `Network eactivate` MLP, but it doesn't make any sense for automation.
#### What Happened Instead
- No MLP tables in DB  
  ![database_ wordpress - adminer-000643](https://cloud.githubusercontent.com/assets/1511122/18089528/16d495dc-6ec9-11e6-80a4-ccd0f5e1bc24.png)
- Languages list is empty  
  ![edit site_ wordpress demo network admin_ wordpress demo sites wordpress-000642](https://cloud.githubusercontent.com/assets/1511122/18089476/dceccb32-6ec8-11e6-8ffc-369275e5b427.png)

**Comment by dnaber-de** [comment]
Can you run `sudo -E -u www-data wp --path=/var/www/html plugin activate multilingual-press --network --debug`? What does it show?

**Comment by dimitrystd** [comment]
No errors, and no tables.
```
root@8ba004845e92:/var/www/html# sudo -E -u www-data wp --path=/var/www/html plugin activate multilingual-press --network --debug
Debug (bootstrap): No readable global config found (0.009s)
Debug (bootstrap): No project config found (0.01s)
Debug (bootstrap): No package autoload found to load. (0.142s)
Debug (bootstrap): ABSPATH defined: /var/www/html/ (0.143s)
Debug (bootstrap): Begin WordPress load (0.144s)
Debug (bootstrap): wp-config.php path: /var/www/html/wp-config.php (0.144s)
Debug (bootstrap): Set URL: 192.168.99.100/ (0.146s)
Debug (bootstrap): Loaded WordPress (0.429s)
Debug (bootstrap): Running command: plugin activate (0.43s)
Success: Plugin 'multilingual-press' network activated.
```
In additional i can say that we develop own plugin which verifies MLP installation and our plugin detects it successfully, but nothing work because lack of tables.

**Comment by dnaber-de** [comment]
Does it install the tables correctly on the same instance if you activate it via wp-admin GUI?

**Comment by dimitrystd** [comment]
Of course. What i do now, go to `/wp-admin/network/plugins.php` and manually `Network Deactivate` and then `Network Activate` it. 
I can try to prepare minimal docker script to reproduce it if it works for you (i do this in docker and can remove all useless stuff).

**Comment by dimitrystd** [comment]
Created minimal docker image to reproduce bug:
* Download files from [gist](https://gist.github.com/dimitrystd/42bdf5395a1e3f09a07519baf537c6c2)
* Build image and run it as described in readme. You can also use prebuild image `docker pull dmitriy/mlp-wpcli-bug`
* Just in case run log looks like
```
$ docker run -it --rm -p 80:80  -e WP_URL=http://192.168.99.100 mlp-wpcli-bug
=> MySQL not configured yet, configuring MySQL ...
=> Setting MySQL bind address to have access from the Docker host
=> Starting MySQL
=> Waiting till MySQL is started
 * Starting MySQL database server mysqld
 * Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.
=> Creating WordPress db
=> Creating MySQL WP user and granting external access
=> Apache is not configured yet, configuring Apache ...
=> Setting ServerName
=> WordPress is not configured yet, configuring WordPress ...
=> Installing WordPress
sh: 1: /usr/sbin/sendmail: not found
Success: WordPress installed successfully.
Set up multisite database tables.
Added multisite constants to 'wp-config.php'.
Success: Network installed. Don't forget to set up rewrite rules.
sh: 1: /usr/sbin/sendmail: not found
sh: 1: /usr/sbin/sendmail: not found
Success: Site 2 created: 192.168.99.100/es/
Installing MultilingualPress (2.4.7)
Downloading install package from https://downloads.wordpress.org/plugin/multilingual-press.2.4.7.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Plugin 'multilingual-press' network activated.
Start apache
```
* Open in browser http://<docker_machine_ip_address>/wp-admin/network/site-settings.php?id=1&extra=mlp-site-settings
 * Credentials `admin`:`admin`
* Try to select language
![edit site_ wordpress demo network admin_ wordpress demo sites wordpress-000658](https://cloud.githubusercontent.com/assets/1511122/18468501/f815d11c-79ac-11e6-854e-0f4137244b82.png)

**Comment by tfrommen** [comment]
Hi all,

I just wanted to let you know that I found the problem: the [check for the _correct WordPress admin page_](https://github.com/inpsyde/multilingual-press/blob/7ed9ac58c8ef4ff78ad6f6409615c31bbc6da9d5/src/Installation/SystemChecker.php#L200) fails - because we are in WP-CLI context.

I can make the activation work by adding this before the `! is_admin()` check:
```php
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    return true;
}
```

The problem with this is that the whole installation routine will then run *for every single WP-CLI command* - which is not something I would want it to.

I am no WP-CLI expert, so I don't know how to best circumvent this, yet.

Any ideas?

I will also try to get in touch with Daniel Bachhuber.

**Comment by danielbachhuber** [comment]
WP-CLI has a hook system you can leverage:

```
if ( class_exists( 'WP_CLI' ) ) {
	WP_CLI::add_hook( 'after_invoke:plugin activate', function(){
		mlp_db_create(); // or whatever the function name is
	});
}
```

See https://wp-cli.org/docs/internal-api/wp-cli-add-hook/

If you want more precision, you'd need to check that `multilingual-press` is within the set of plugins begin activated, because more than one plugin can be activated at a time.

**Comment by tfrommen** [comment]
Should be fixed in https://github.com/inpsyde/multilingual-press/commit/52279155e0780a0ed769fe26a002c4ebaf17d0cb.

**Comment by Dinamiko** [comment]
I just tested in https://github.com/inpsyde/MultilingualPress/tree/refactor/term-translator and it worked, MultilingualPress tables were created correctly.
