### ISSUE TITLE
Add the transfer of all images to the translated sites

### ISSUE THREAD

**Issue by nullbytes** [inpsyde/MultilingualPress#242]
#### Version Information
- WordPress: 4.6.1
- MultilingualPress: 2.4.7
#### Steps to Reproduce
1. create a new post with many images
2. translate the post into other languages
3. 
#### What I Expected

All images of the new post should be transferred to the new sites
#### What Happened Instead

Only the post thumbnail can be transferred. It would be nice to have a top-level setting that will copy all images of a post to a new site and add them to the new created post on that site.

**Comment by RikeOne** [comment]
Hey nullbytes,
do you still got a solution for your problem?
I'm interested in this solution too!
Thank you in advance!

**Comment by Dinamiko** [comment]
For MultilingualPress version 2 we recommend using https://github.com/bueltge/multisite-global-media. For new version 3 we can plan to add it as an extension if there is enough demand for this feature.
