### ISSUE TITLE
Multilingual-press an polylang 2.1.1 together

### ISSUE THREAD

**Issue by kochhase** [inpsyde/MultilingualPress#252]
#### Version Information
* WordPress: 4.7.2
* MultilingualPress: latest 2.5.2

#### Steps to Reproduce
I have to use Multilingual-press an polylang 2.1.1 together in a multisite installation. Multilingual-press can only be used network-wide. I there a possibilty to only aktivate Multilingual-press on some multisite page ID ´s
thanks for help

**Comment by tfrommen** [comment]
Hi,

MultilingualPress can only be **activated** network-wide, yes. However, it is only **active** on sites that have a (MutlilingualPress) language assigned and are related to at least one other site.

Does that help?

Cheers,
Thorsten
