### ISSUE TITLE
Duplicate draft posts

### ISSUE THREAD

**Issue by Flowgram** [inpsyde/MultilingualPress#253]
#### Version Information
* WordPress: 4.7.3
* MultilingualPress: 2.5.3

#### Steps to Reproduce
1. Install sub-directory multisite
2. Install and activate MultilingualPress
3. Set main site to English
4. Make a new site and create a relationship between the two
5. In MultilingualPress settings untick Advanced Translator
6. Create a new post on the first site and tick the box to translate it on the new site, click Publish

#### What I Expected

To see one post on the new site.

#### What Happened Instead

Two draft posts appear on the new site, only one has the connection to the original post.

Thank you for your time

**Comment by tfrommen** [comment]
Thanks for the issue, I can confirm this.

**Comment by tfrommen** [comment]
Closed in 1756ea30cd2be35c2981d6d10dc1bea3251b3b4e.
