### ISSUE TITLE
Untranslated Posts not populating the dashboard widget

### ISSUE THREAD

**Issue by Flowgram** [inpsyde/MultilingualPress#254]
#### Version Information

* MultilingualPress: 2.5.4
* WordPress: 4.7.3
* PHP: 5.4.12 + 7.0.3

#### Steps to Reproduce

1. Create a new post on Site 1 and tick the box to translate it for Site 2, click Publish.
2. Go to the Site 2 dashboard

#### What I Expected

I expected to see the new post listed under Untranslated Posts in the dashboard widget.

#### What Happened Instead

In the Untranslated Posts box I see the following titles: 
"Pending Translations for Site 1" 
"Pending Translations for Site 2"
"Pending Translations for Site 3"

but no actual posts. Same goes for all sites on the Network.

Also, as I'm on the Dashboard for Site 2, I wouldn't expect to see any titles or other mention of untranslated posts on any of the other sites. This dashboard should only show info related to the site that it's on.

Ideally there should be another dashboard widget (maybe on the Network home?) that lists the untranslated posts from across all the sites on the Network.

Thanks

**Comment by tfrommen** [comment]
Nice that we agree here. We have pretty much all of this listed in #190 already. ;)

Anything missing in your opinion, or can I close this as duplicate?

**Comment by Flowgram** [comment]
Ahh sorry, I must have missed that issue.  Feel free to close this one, everything seems to be covered in #190. Any idea of ETA of this feature? 


I'm currently considering using MultilingualPress in on a site we're about to start building, but to be honest the apart from the linking of the post in the back-end.

We rely heavily of Advanced Custom Fields and Multisite Post Duplicator works pretty well in this regard.

**Comment by Flowgram** [comment]
@tfrommen Ahh sorry, I must have missed that issue. Feel free to close this one, everything seems to be covered in #190. Any idea of an ETA of this feature?

I'm currently considering using MultilingualPress on a site we're about to start building, but to be honest, apart from displaying a link between the posts in the back-end and without the dashboard widget, it's a very light touch plugin at present.

We rely heavily of Advanced Custom Fields, so I was hoping to combine MultilingualPress with another plugin called Multisite Post Duplicator which does a good job of duplicating posts and fields across sites. I'd then link the posts manually with MultilingualPress if need be, but without a dashboard widget showing the status of translations, there doesn't seem to be a great advantage.

**Comment by tfrommen** [comment]
Okay, closing this now.

>Any idea of an ETA of this feature?

No, sorry. Although _annoying_, it doesn't have a high priority right now, to be honest.

> apart from displaying a link between the posts in the back-end and without the dashboard widget, it's a very light touch plugin

I think I don't understand. Are you saying there isn't much functionality in MultilingualPress besides _linking_ posts and having a (broken) dashboard widget?

That surely depends on what you want to (or can) use. MLP comes with a lot more features. If you only need the two mentioned, then MLP is not for you, or for this website at least.

Cheers,
Thorsten
