### ISSUE TITLE
Different relationships between two sites

### ISSUE THREAD

**Issue by asadowski10** [inpsyde/MultilingualPress#256]
Hi team,

My client is reminding me of an abnormal behavior. Some relationships seem broken.
The relationship between site A > B is different from the relationship between site B > A
I can not understand the problem and solve it.

#### Version Information

WordPress: 4.4.5
MultilingualPress: 2.4.8

#### Steps to Reproduce

1. We have content "FR1" on site 1 ( French version ) 
2. We link the page to a content  "EN1" on site 2 ( English version )
3. On french site (site 1) the relation is OK 
4. On english site ( site 2 ) the relation is NOT OK, "EN1" is linked to an other content of site 1 "FR21"...

Thanks a lot,
Alex

**Comment by tfrommen** [comment]
Hey Alex,

I am suspecting incorrect (i.e., semi-duplicate conflicting) relationship data in your database. However, I'm not sure why the query result is different between the individual sites (but consisten for each single site)...

Can you please run the following query (with an adapt table prefix**!**), and tell me if you got any results:

```mysql
SELECT
    mlp1.*
FROM
    wp_multilingual_linked mlp1, wp_multilingual_linked mlp2
WHERE
    mlp1.ml_source_blogid = mlp2.ml_source_blogid
    AND mlp1.ml_source_elementid = mlp2.ml_source_elementid
    AND mlp1.ml_blogid = mlp2.ml_blogid
    AND mlp1.ml_type = mlp2.ml_type
    AND mlp1.ml_elementid != mlp2.ml_elementid
```

Cheers,
Thorsten

**Comment by tfrommen** [comment]
Any news on this, @asadowski10?
