### ISSUE TITLE
Duplicate draft is created each time post is previewed

### ISSUE THREAD

**Issue by NaurisSadovskis** [inpsyde/MultilingualPress#260]
Hi all,

thanks for the plugin! We are experiencing the same issue as described in #253 .

Wondering if you can help!

#### Version Information

* PHP: 7
* WordPress: 4.7.4 
* Multilingual Press: 2.5.4

#### Steps to Reproduce

1. Create multiple sites
2. Go to the main site and create a post
3. Add content to the main post body and copy it to other locales
4. Scroll back to the top and click preview
5. It will open a new window with the post preview

#### What I Expected
1. Preview should not create additional drafts in each locales

#### What Happened Instead
2. Each preview triggered additional draft creation in other locales

**Comment by tfrommen** [comment]
Hey,

thanks for reporting this.

I just fixed the underlying issue, so you can expect a new release _soon_.

**Comment by tfrommen** [comment]
Fixed (for `2.5`) in https://github.com/inpsyde/MultilingualPress/commit/ee8cd4591fbe26a74d547c0d584432ffcbb699d5.
