### ISSUE TITLE
Object Cache not purged

### ISSUE THREAD

**Issue by Chrico** [inpsyde/MultilingualPress#261]
#### Version Information

* PHP: any
* WordPress: latest
* MLP: 2.6.x

#### Steps to Reproduce

1. Clean installation of a Multisite with min. 2 connected Blogs (e.G. DE <-> EN)
2. Add dropin `object-cache.php`  with some persitant cache (Memcache, APC(u), ..)
3. Create a new post (e.G. post-type=page) in DE
4. Create a new post (e.G. post-type=page) in EN
5. Insert into frontend:
```php
mlp_show_linked_elements( [
	'echo'              => false,
	'link_text'         => 'language_short',
	'show_current_blog' => true,
] );
```
6. View post DE. 
7. `mlp_show_linked_elements` prints the link to `home_url()` for EN Blog
8. Visit edit-post of DE post, connect the EN post and save.
9. View post DE again.

#### What I Expected
The `mlp_show_linked_elements()` should now show the EN page in navigation.

#### What Happened Instead
The `mlp_show_linked_elements()` does still show the link to the EN home page. 

#### Why?
This happens, because `mlp_show_linked_elements()` calls internally [`Mlp_Helpers::show_linked_elements()`](https://github.com/inpsyde/MultilingualPress/blob/2.6/src/inc/common/Mlp_Helpers.php#L356) which calls [`$api->get_translations()`](https://github.com/inpsyde/MultilingualPress/blob/2.6/src/inc/common/Mlp_Helpers.php#L407).

The method [Mlp_Language_Api::get_translations()](https://github.com/inpsyde/MultilingualPress/blob/2.6/src/inc/language-api/Mlp_Language_Api.php#L200) uses interally [`wp_cache_set()`](https://github.com/inpsyde/MultilingualPress/blob/2.6/src/inc/language-api/Mlp_Language_Api.php#L356) to store the results based on the [`$args`](https://github.com/inpsyde/MultilingualPress/blob/2.6/src/inc/language-api/Mlp_Language_Api.php#L206) which are the cache key. 
Sadly it is not purged when a Post is updated/created/deleted. The key generation is also not safe to trust, because it does not have any context where it is used. The output can vary on every page (includes Archive, Single, CPT, ..) in frontend.

**Comment by tfrommen** [comment]
Fixed in https://github.com/inpsyde/MultilingualPress/commit/e9b0735bc2d55206ba1c2cbf8b70b137f5e5b84c.
