### ISSUE TITLE
Current/active language

### ISSUE THREAD

**Issue by strarsis** [inpsyde/MultilingualPress#263]
This may sound trivial - but how to find reliably out, being best practice, (e.g. as another plugin) what the current/active language is? Is there a function or mechanism that can be used? I wasn't able to find it in the documentation/wiki pages.

**Comment by tfrommen** [comment]
Hi there,

depending on what exactly a _language_ is for you, you can just use [`mlp_get_current_blog_language()`](https://github.com/inpsyde/MultilingualPress/blob/60b1b30f6ba910d04f6f6cbc8a1a9717c02529f3/src/inc/functions.php#L38). By default, this gives the _locale_ string for the current language (e.g., `en_US`), but you can pass `true` as first and only argument to only get the language part (e.g., `en`).

Cheers,
Thorsten

**Comment by strarsis** [comment]
Thanks, this answers my question! Documenting these functions would be great.

**Comment by tfrommen** [comment]
True. And we will, some time soon.

**Comment by strarsis** [comment]
@tfrommen: What is the difference between 
[`get_current_site_language()`](https://github.com/inpsyde/MultilingualPress/blob/0bd4961e6fb16a76bb292c7bed52ccb5a0d42231/inc/functions.php#L323) and [`mlp_get_current_blog_language()`](https://github.com/inpsyde/MultilingualPress/blob/60b1b30f6ba910d04f6f6cbc8a1a9717c02529f3/src/inc/functions.php#L38) ?

**Comment by tfrommen** [comment]
These are two completely different versions of the plugin. The current stable one lives in the `2.6` branch, and that's where I linked to. The function is `mlp_get_current_blog_language()`, in the global namespace.

In the upcoming version of MultilingualPress - this will be a major release, and in fact a separate plugin - the function is called `get_current_site_language()`, and it is to be found in the `Inpsyde\MultilingualPress` namespace.
