### ISSUE TITLE
Custom Post Type Support checked status

### ISSUE THREAD

**Issue by Dinamiko** [inpsyde/MultilingualPress#269]
#### Version Information

* PHP: 7.0.15
* WordPress: 4.8
* MultilingualPress: refactor/term-translator branch

#### Steps to Reproduce

1. Register a Custom Post Type
2. Go to `Settings / MultilingualPress / Custom Post Type Support`, check `Custom Post Type Support` checkbox and click `Save Changes` button. 
3. At the bottom in `Custom Post Type Support` check your Custom Post Type name checkbox and click `Save Changes` button. 

#### What I Expected
Custom Post Type checkbox checked.

#### What Happened Instead
Custom Post Type checkbox not checked.

**Comment by tfrommen** [comment]
Fixed in https://github.com/inpsyde/MultilingualPress/commit/ac5c9b75a349aa19fcd8dca341655451aea36107.
