### ISSUE TITLE
Links aren't removed when deleting a post

### ISSUE THREAD

**Issue by diedexx** [inpsyde/MultilingualPress#276]
#### Version Information

* PHP: any
* WordPress: any
* MultilingualPress: 2.7.1

#### Steps to Reproduce

1. Create a post
2. Translate/link the post by creating a new post
<img width="525" alt="edit_product_ _yoast_ _wordpress" src="https://user-images.githubusercontent.com/5352634/28967635-5f500090-791c-11e7-9fad-5453ada115c9.png">

3. Publish the newly linked post
4. Delete the newly linked post

#### What I Expected
I expected that the links connecting the two posts to disappear. Or at least that the deleted post wouldn't be linked in the hreflang links

#### What Happened Instead
The deleted post is still linked referenced, even though the post is no longer accessible.
<img width="614" alt="yoast_seo__the__1_wordpress_seo_plugin_ _yoast" src="https://user-images.githubusercontent.com/5352634/28967664-8bda1614-791c-11e7-860c-4732dd1dc8f6.png">

**Comment by tfrommen** [comment]
Relationship data should not be deleted when a post gets trashed (only when it actually gets permanently deleted). But yes, trashed posts should not be included in the `hreflang` output - as well as potential other things...

**Comment by Dinamiko** [comment]
Hi @diedexx, 

We have just implement it, can you please test the new branch, `2.8`, which should fix both issues.

Thanks,
Emili

**Comment by diedexx** [comment]
Hi, Thank's for looking into this so quickly! It looks like it works! However, there's one small issue; the links are shown when there's just a single (available) linked post left. This results in solely a self-reference without any translated alternatives. I don't think it does any harm seo-wise, but it isn't necessary to add hreflang links to a page without translations.
<img width="565" alt="aaaaaaabbbb_-_yoast" src="https://user-images.githubusercontent.com/5352634/29026033-f6c8d8ac-7b79-11e7-8021-b2093cd5c0c9.png">

**Comment by tfrommen** [comment]
Hi @diedexx,

yes, I saw that last week already, but wanted to make sure everything is working.
In the `2.8` branch, there is a new filter `multilingualpress.render_hreflang` that people can use to either _force_ or _prevent_ hreflang rendering.
By default, links will get rendered as soon as there are 2 or more.

I guess this is something you are fine with, right?

**Comment by diedexx** [comment]
Hi @tfrommen, that's perfect, thanks :+1:

**Comment by tfrommen** [comment]
Cool, then I close this now.

Implemented in 8fa5897fc395112d0d03d416c24a38975ea81e18.
