### ISSUE TITLE
Passing content_id to get_translations fails on term pages

### ISSUE THREAD

**Issue by diedexx** [inpsyde/MultilingualPress#279]
#### Version Information

* PHP: 7.0
* WordPress: any
* MultilingualPress: dev-2.8

It appears that `Mlp_Language_Api`'s `get_translations()` function fails to get translations when the following is true:
- `get_translations()` is called with the 'content_id' argument
- The current page isn't a valid post-type. A (post) category for example.

When these are true, the arguments (as provided by `prepare_translation_arguments()`) do not contain a value for `post_type`.
The post type is set to the result of `get_request_post_type()`, which in its turn calls `get_query_var`, which only looks up the post type of the current post, not the post which id was passed in the arguments.

This results in 0 translations, because none of the translations meet the "stored_type = passed_type" requirement in the query (`Mlp_Content_Relations::get_relations`)

**Comment by tfrommen** [comment]
I don't understand how **any** `post_type` can conflict with a **term** query (i.e., `'type' => 'term'`).

Can you please provide the whole `$args` that you pass?

**Comment by diedexx** [comment]
Sorry, I was mistaken. The `post_type` argument doesn't cause the query to fail, it's the value of the `type` argument.

These are the values of the args:

<img width="253" alt="mlp_language_api_php_-_yoast_com-ms_-____dev_yoast_com-ms_" src="https://user-images.githubusercontent.com/5352634/29157145-cf333ade-7da5-11e7-800f-d6ddae567b75.png">


The executed query:
```sql
SELECT t.ml_blogid as site_id, t.ml_elementid as content_id
FROM wp_multilingual_linked s
INNER JOIN wp_multilingual_linked t
ON s.ml_source_blogid = t.ml_source_blogid
	AND s.ml_source_elementid = t.ml_source_elementid
	AND s.ml_type = t.ml_type
WHERE s.ml_blogid = 1
	AND s.ml_elementid = 877647
	AND s.ml_type = 'term'
```

When using the WP-API, the term argument remains empty which results in:
```sql 
	AND s.ml_type = ''
```

the ml_type is set to "post" in the database, which is why no results are found.

It's easily fixed by passing the correct `type` argument in my implementation, but it might be nice to have it detect the type of the content of which the `content_id` was passed in the arguments by default.

**Comment by tfrommen** [comment]
> it might be nice to have it detect the type of the content of which the content_id was passed in the arguments by default.

Maybe I'm missing something here, but how should this be detectable? I mean, there is a post with ID 1, there is term with term taxonomy ID 1, there is a user with ID 1 (thinking about translating user metadata in the future), ... You simply have to pass a type (unless you are doing a front-end request and you are fine with what its actual type.

**Comment by diedexx** [comment]
Oh right, I did not realise those all have their own id numbering. Seems fair to just pass the right arguments for the situation.
