### ISSUE TITLE
Installing the plugin from WP CLI the mlp_languages is not created

### ISSUE THREAD

**Issue by davidetaddei** [inpsyde/MultilingualPress#281]
#### Version Information

* PHP: 7.1.8 (Docker image php:7.1.8-apache)
* WordPress: 4.8

#### Steps to Reproduce

1. Launch installation with 

`docker exec -itu www-data CONTAINER_NAME php wp-cli.phar plugin install https://downloads.wordpress.org/plugin/multilingual-press.2.8.1.zip --force --activate-network`

2. There is no mlp_languages table in the database.

#### What I Expected
I expected to find language list in the dropdown under MultilingualPress tab (/wp-admin/network/site-settings.php?id=1&extra=mlp-site-settings).

#### What Happened Instead
There is not language list in the dropdown under MultilingualPress tab (/wp-admin/network/site-settings.php?id=1&extra=mlp-site-settings). Only the Choose Language label is available.

**Comment by tfrommen** [comment]
duplicate #230

----

Hi,

this is a known issue, see #230, and it has already been fixed for the upcoming major release.

We will discuss fixing this for 2.x as well...

**Comment by davidetaddei** [comment]
Thank you Thorsten, I read the #230. I agree it would be useful to make the plugin WP CLI compliant even in this version at least for the basic function (installation, activation, etc..)

**Comment by tfrommen** [comment]
Fixed in https://github.com/inpsyde/MultilingualPress/commit/3919ebdbc202065a8ee1916efce49e2dbcb94ee0.
