### ISSUE TITLE
Feature request: mlp_allowed_object_taxonomies

### ISSUE THREAD

**Issue by luisarn** [inpsyde/MultilingualPress#282]
I would like to be able to disable the translation select box for certain taxonomies.

By default MLP loads all the taxonomies registered to the allowed post types and doesn't have a filter to change it.

I modified the Mlp_Term_Translation_Controller.php line 181 from:

`return get_object_taxonomies( $post_types );
`

to:

`return apply_filters( 'mlp_allowed_object_taxonomies', get_object_taxonomies( $post_types ) );
`

Hope you can include this into the next release.

Best regards,
Luis

**Comment by tfrommen** [comment]
Hi Luis,

thanks for the issue. This has already been [implemented for the next major version](https://github.com/inpsyde/MultilingualPress/blob/7cb867894222e6f897c0970e1e63d329fd3d1856/src/Translation/Term/ActiveTaxonomies.php#L61), but sure, we can add it for 2.x as well.

Cheers,
Thorsten

**Comment by tfrommen** [comment]
Implemented in https://github.com/inpsyde/MultilingualPress/commit/68b0e9b72150e36cd6d6cdf6d55de735b3da3006.
