### ISSUE TITLE
Create hreflang relationships between sites?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [inpsyde/MultilingualPress#285]
We are using WordPress multisite and your MultilingualPress plugin to handle our multilingual website. Because of WooCommerce limitations, however, we still have to use distinct domains for different currencies. For example:

- GBP : .co.uk
- EUR
-- EN : .eu
-- DE : .eu/de
-- ES : .eu/es
- CHF
-- DE : .ch/de
-- FR : .ch/fr

And so on. While MultilingualPress works perfectly for creating hreflang relationships within a multisite, we're having difficulty coming up with a scalable solution to create relationships across domains. To be clear, we aren't looking to manage all the websites and translations from a single domain like MultilingualPress does within a multisite; we only want to create the hreflang relationships for content across domains.

Is this something that can be done with MultilingualPress? If not through the WordPress dashboard, perhaps by manually adding values to the DB? Any suggestions or pointers are appreciated.

EDIT: I forgot to mention that we're already utilizing shared user tables between the sites with custom plugins to sync permissions. We'd be OK doing something similar for hreflang tags if it's scalable.

**Comment by tfrommen** [comment]
Hi there,

I think I should mention one thing: having a multisite does **not** mean you can only have a single domain (with either sub-directories or sub-domains).
It's perfectly possible (and I good idea) to have actual domains, such as `example.co.uk`, `example.eu` or `example.ch`, and then also have sub-directories.

This means you can achieve the setup from your above table in a single multisite, without the need for any user table sync plugin etc.

If you actually do not want to have your websites in a single multisite, this is hard(er) to do.
While there are [several](https://github.com/inpsyde/MultilingualPress/blob/60c1b002b31c4e072f8591f8b2608c4a650c3305/src/inc/hreflang-header/Mlp_Hreflang_Header_Output.php#L193) [filters](https://github.com/inpsyde/MultilingualPress/blob/60c1b002b31c4e072f8591f8b2608c4a650c3305/src/inc/hreflang-header/Mlp_Hreflang_Header_Output.php#L92) for the `hreflang` links/headers, you would have to have some sort of map between the content elements of all the (multi)sites. This is nothing I would suggest to do/have.

**Comment by ahmed-sigmalux** [comment]
It's been a while since we installed WordPress so I didn't realize that domain mapping became a native feature in version 4.5. We wanted to limit hacks and workarounds and, since domain mapping wasn't a native feature, we never seriously considered. Thanks for setting me straight!

Now I need to read up on how to convert / merge separate sites into a an existing multisite installation.
