### ISSUE TITLE
Post translator not displaying for users without the edit_post capability

### ISSUE THREAD

**Issue by luisarn** [inpsyde/MultilingualPress#286]
#### Version Information

* PHP: 7.1.9
* WordPress: 4.8.2

#### Steps to Reproduce

1. Create a custom post type (content_page) with custom capabilities name using map_meta_cap:
content_page_edit, content_page_delete, content_page_publish, ... and so on.
2. Create a custom role (Content Editor) and assign those capabilities to that role and assign an user to that role
3. Enable the Custom Post Type Translator on Multilingual Press settings for the post type "content_page"
4. Use the Content Editor user to edit the content_page custom post type

#### What I Expected

To be able to use the Post Translator.

#### What Happened Instead

Post Translator not showing up.

#### Proposed solution

After digging into the code on Mlp_Translation_Metabox.php I found out that the required capabilities are hard coded on line 186 (edit_posts) and 189 (edit_post):

`	private function is_translatable_by_user( WP_Post $post, $blog_id ) {

		$blog_id = absint( $blog_id );

		$remote_post = $this->data->get_remote_post( $post, $blog_id );
		if ( isset( $remote_post->dummy ) && $remote_post->dummy === true ) {
			return current_user_can_for_blog( $blog_id, 'edit_posts' );
		}

		return current_user_can_for_blog( $blog_id, 'edit_post', $remote_post->ID );
	}`

So I updated the function / method to get the current post type mapped edit_posts and edit_post capability to make it work:

`	private function is_translatable_by_user( WP_Post $post, $blog_id ) {

		$blog_id = absint( $blog_id );

		$remote_post = $this->data->get_remote_post( $post, $blog_id );
		// Need to get current CPT edit post cap.
		$post_type = get_post_type_object( $post->post_type );
		if ( isset( $remote_post->dummy ) && $remote_post->dummy === true ) {
			return current_user_can_for_blog( $blog_id, $post_type->cap->edit_posts );
		}
		return current_user_can_for_blog( $blog_id, $post_type->cap->edit_post, $remote_post->ID );
	}`

Best regards,
Luis

**Comment by tfrommen** [comment]
Hi there,

good catch! 👍

We already [fixed this for the next major version](https://github.com/inpsyde/MultilingualPress/blob/1e755e840ce1c0694191050dc143b0847e642b51/src/Translation/Post/RelationshipPermission.php#L58-L68), but simply forgot to backport this, which we wanted to and now will do.

**Comment by tfrommen** [comment]
Fixed in https://github.com/inpsyde/MultilingualPress/commit/f8ebb23e476cf9a379625a30f144e184c458d5bb.
