### ISSUE TITLE
MultilingualPress creating invalid HTTP link headers

### ISSUE THREAD

**Issue by ahmed-sigmalux** [inpsyde/MultilingualPress#287]
#### Version Information

* PHP:  7.1.10
* WordPress:  4.8.2

#### Steps to Reproduce

1. Add languages en_US, de_DE, and fr_FR
1. Create a page and set a relationship between all 3 languages
1. Load the page and inspect the HTTP headers

#### What I Expected

Per Google's support content at https://support.google.com/webmasters/answer/189077?hl=en, multiple hreflang values should be comma separated in a Link header:

```Link: <http://www.example.com/en/>; rel="alternate"; hreflang="en_US", <http://www.example.com/de/>; rel="alternate"; hreflang="de_DE", <http://www.example.com/fr/>; rel="alternate"; hreflang="fr_FR"```

#### What Happened Instead

MultilingualPress is generating separate Link headers for each language like so:

```
Link: <http://www.example.com/en/>; rel="alternate"; hreflang="en_US"
Link: <http://www.example.com/de/>; rel="alternate"; hreflang="de_DE"
Link: <http://www.example.com/fr/>; rel="alternate"; hreflang="fr_FR"
```

**Comment by ahmed-sigmalux** [comment]
Upon further testing, I see this issue only occurs when using Nginx connecting to PHP-FPM via fastCGI. Is there anyone else running Nginx who can test and confirm?

**Comment by tfrommen** [comment]
Hi there,

as you found out yourself, the headers are added in the _standard_ way, and usually end up being part of a single `Link` header with comma-separated values.

No idea what's causing this behavior, and I never heard of something like this before. Doing a quick search myself, I only found [this slightly related question](https://stackoverflow.com/q/44600163/2117788).

Closing this for now, but **please** leave any kind of feedback that you might get and want to share or discuss.

Thanks,
Thorsten
