### ISSUE TITLE
Copying the content of a scheduled (future) post doesn't work

### ISSUE THREAD

**Issue by davilera** [inpsyde/MultilingualPress#296]
#### Version Information

* PHP: 7
* WordPress: 4.8.3

NOTE: this issue might be related to #295.

#### Steps to Reproduce

1. Create a new post in one language
2. Set a future date
3. Schedule the post
4. Look for the Translation meta box
5. Click on _Copy source post_ (and maybe enable the checkbox for copying the feat. image)
6. Click on _Change relationship_
7. Select _Create new post_
8. Click on _Save and reload this page_

#### What I Expected

The translated post should have the same title, slug, post content, excerpt (and possibly featured image) as the original post.

#### What Happened Instead

Only the title and slug were copied. Post content, excerpt, and featured images remain empty.

If I apply the "solution" described in #295 (that is, re-copying the post and saving it using the _Update_ button in the _Publish_ meta box) doesn't work.

**Comment by davilera** [comment]
I looked at the source code and there are a couple of checks that might explain this behavior.

In `inc/post-translator/Mlp_Translatable_Post_Data.php` line 506, there's a function that checks if `is_connectable_status`. The _if_ condition doesn't include the `future` status.

In `inc/post-translator/Mlp_Save_Post_Request_Validator.php` line 65, there's a function that checks if a post `is_real_revision`. One of the _if_ conditions is also missing the `future` status.

I think that adding said status in those _if_ statements fixes the issue, but I'm not 100% sure (nor do I know if other parts of the code should be addressed).

**Comment by tfrommen** [comment]
Hi again,

leaving aside all the things related to how _Create new post_ works, you re right that scheduled posts cannot be translated right now.

We already fixed this for the new major version of MultilingualPress, but now I also included this to be released in the next minor update.
If you need this now, you can add the `'futur'` post status yourself, in the `is_connectable_status()` method. The request validator code is OK, althought I simplified it a little bit. Nothing to do for you, though.

Thanks for reporting this,
Thorsten

**Comment by Dinamiko** [comment]
This is already merged into master.
