### ISSUE TITLE
Uncached SQL calls

### ISSUE THREAD

**Issue by spacedmonkey** [inpsyde/MultilingualPress#297]
#### Version Information

* PHP: 7.1
* WordPress: 4.9 

One every front end page load, there is an uncached query run. See attached a screenshot of the stace trace. 
![screenshot from 2017-11-17 12-02-11](https://user-images.githubusercontent.com/237508/32946522-c66ae874-cb8f-11e7-8516-6f4fece15390.png)

This seems pretty wasteful, as the query is a lookup on the related site. As these related sites do no change that much, it should be simple enough to implement basic caching, as linking of the sites, is a user action, and cache invalidation should be easy. 

Let me know if you want a PR for this.

**Comment by spacedmonkey** [comment]
Looking more into this, I noticed there is another uncached call. 

![screenshot from 2017-11-17 14-56-51](https://user-images.githubusercontent.com/237508/32953515-5ab2f806-cba8-11e7-9a85-074295267bc1.png)

**Comment by Dinamiko** [comment]
This is already done in new MultilingualPress version 3. Regarding the release it will probably be during September 2018.
