### ISSUE TITLE
Stop expensive SHOW Table query

### ISSUE THREAD

**Issue by spacedmonkey** [inpsyde/MultilingualPress#298]
On every page load a query to list of site table is run. I am not sure what this query is used for, but it is expensive on large scale WordPress multisite installs. If you have say 30K+ tables in a database, a SHOW table with a like, it slow to return. 

I understand that you want all tables for a site, wouldn't `$wpdb->tables('blog')` cut it here? Or do you want tables installed by users as well. I am not sure how you can add support for custom tables. Personally I think it is better to stick to core tables. 

![screenshot from 2017-11-17 12-26-58](https://user-images.githubusercontent.com/237508/32947206-a4363b16-cb92-11e7-9048-66007a36e192.png)

If you want all tables, then call if once, cache it. Then invalid the cache when the `dbdelta` function is called (using the `dbdelta_queries` filter).

**Comment by spacedmonkey** [comment]
I have been working on a patch for this and noticed that you working on a big refactor for version 3. 

Because I don't want to put a PR in at this time of change, I thought I would give you some example code to show you I would do caching. 

```php
private function get_names_from_db() {

		$query = $this->get_sql_for_all_tables( $this->wpdb->base_prefix );
		$key   = md5( $query );
		$cache_group = 'multilingual-press';
		wp_cache_add_global_groups( $cache_group );
		$names = wp_cache_get( $key, $cache_group );
		if ( false === $names ) {
			$names = $this->wpdb->get_col( $query );
			wp_cache_add( $key, $names, $cache_group );
		}
		add_filter( 'dbdelta_queries', function ( $queries ) use ( $key, $cache_group ) {
			wp_cache_delete( $key, $cache_group );

			return $queries;
		} );
		// Make sure there is something in the array, so we don't try that again.
		if ( empty( $names ) ) {
			return array( $this->no_tables_found );
		}

		return $names;
}

```

To briefly explain this code. Add 'multilingual-press' as a global cache group (this means that the same cache is used for all sites). Check to see if key (md5 of query) is in object cache. If not cache, run the query and save in cache. 

There is a hook into `dbdelta_queries`, that runs whenever a database is created in WP. If the delta is run, then invalid the table list cache.

**Comment by tfrommen** [comment]
Hey Jonny,

appreciate your investment in this, but yes, as you found out, `master` has nothing to do with the current w.org plugin, which is the 2.x version branch. This repository contains the work of the upcoming major version 3, which will be completely different, structurally speaking.

In the course of the refactoring, we completely [killed all kinds of caching](https://github.com/inpsyde/MultilingualPress/commit/fac142730cfcbe98bab8da9df3f9b264e9ad12a0) (also for [the SQL query](https://github.com/inpsyde/MultilingualPress/commit/fac142730cfcbe98bab8da9df3f9b264e9ad12a0#diff-b2649c8702ca34cf9dfc9344aece7a3c) you mentioned here), on purpose, and now the plan is to add it back in, in a meaningful way.
In order for this, there is a new dedicated [package for caching](https://github.com/inpsyde/MultilingualPress/tree/master/src/Cache), and we _only_ have to implement this.

----

I'm on parental leave right now, and so will not be involved here again anytime soon, just to let you know. 😉

**Comment by Dinamiko** [comment]
This is already done in new MultilingualPress version 3. Regarding the release it will probably be during September 2018.
