### ISSUE TITLE
Duplicate draft posts when creating 

### ISSUE THREAD

**Issue by fschroiff** [inpsyde/MultilingualPress#300]
#### Version Information

* PHP: 7.1.6
* WordPress: 4.9.1
* mlp: 2.11.0

#### Steps to Reproduce

1. Create post
1. save post as draft / publish post
1. check "Translate this post" (and nothing under "Change relationship")
1. save post as draft / publish

#### What I Expected
One translated draft to appear in the other language's site. 

#### What Happened Instead
Two drafts appeared, one related to the original post, one not.

**Comment by Dinamiko** [comment]
Hi fschroiff,

I'm not able to reproduce this issue, can you please try this:
1 - Try deactivating all other plugins to see if there is a conflict with another plugin. Also try with a default WordPress theme just in case.
2 - Try using Advanced Translator to see if the problem persist or not.

Thanks.

**Comment by Dinamiko** [comment]
@fschroiff We are going to close the issue, feel free to reopen it or create a new one at any time.
