### ISSUE TITLE
MLP minimum WP requirement is currently 4.7, but documentation claims 4.2

### ISSUE THREAD

**Issue by lkraav** [inpsyde/MultilingualPress#301]
#### Version Information
* WordPress: 4.5
* MultilingualPress: 2.11

#### Steps to Reproduce
1. Try to activate MLP
2. Witness 500 error crash

From https://github.com/inpsyde/MultilingualPress/commit/a3ad597294807208a290b3085a1e8cdbc3975367#r26384948

Hi @Dinamiko. I discovered that this line breaks 2.11.0 for WP 4.5, because get_network() is a function for WP 4.6 and up:

`$this->nonce_validator = Mlp_Nonce_Validator_Factory::create( 'duplicate_site', (int) get_network()->site_id );`

I'm not entirely sure why would a nonce validator thing be a part of a PHPCS commit?

Either way, README.md states 2.11.0 compatibility should be WP 4.2+. This seems to be a documentation bug, but also potentially breaks WP sites who lag behind on core version updates, but get offered the incompatible update.

**Comment by lkraav** [comment]
I updated the subject site to 4.6.x now, and found that MLP's current implementation of `wp_parse_url()` is only compatible w/ 4.7.0+, or we generate a PHP warning on every request.

https://github.com/inpsyde/MultilingualPress/blob/v2.11.0/src/inc/Multilingual_Press.php#L184

vs

> 4.7.0 | The $component parameter was added for parity with PHP's parse_url().

https://developer.wordpress.org/reference/functions/wp_parse_url/

**Comment by Dinamiko** [comment]
Hi @lkraav, 

Thanks for the info :) I have just upgraded minimum WP version to 4.7: https://github.com/inpsyde/MultilingualPress/commit/5aa9d474232b0dd6b86d04a98224f9586fa82d91
