### ISSUE TITLE
Getting translations with `include_base` option returns nothing when base site has no relationships

### ISSUE THREAD

**Issue by jedrzejchalubek** [inpsyde/MultilingualPress#304]
Give me a green light 🚥  and I'm happy to make a PR :)

#### Version Information
* MultilingualPress: `2.11.0`

#### Steps to Reproduce
1. Create new site within network without any translations (relations with other sites).
2. Receive translations using API with `include_base` option.
```php
$api = apply_filters('mlp_language_api', null);

$translations = $api->get_translations([
    'site_id' => $blog_id,
    'strict' => false,
    'include_base' => true, // Important
]);
```

#### What I Expected

Receive an array with single Translation object of the site with id specified with `$blog_id`.

#### What Happened Instead

We are receiving an empty array. It is, probably, cased by an early return at: https://github.com/inpsyde/MultilingualPress/blob/938d2bdde9db22087b19317d84b0aef1e10c126f/src/inc/language-api/Mlp_Language_Api.php#L657-L659

**Comment by Dinamiko** [comment]
Hi @jedrzejchalubek,

I´ve checked and went able to reproduce the issue, you have green light 🚥 for the PR :)

Thanks,
Emili

**Comment by Dinamiko** [comment]
It is already merged into master.
