### ISSUE TITLE
Posts archive page translation url feature

### ISSUE THREAD

**Issue by dmorbidi** [inpsyde/MultilingualPress#309]
As a user, when I access to the Archive post page (monthly archive of your site’s Posts, reachable for example through the Archives widget), I get page with a list of standard posts referred to a particular month and year.

But if then I try to change the language site, using for example MLP language menu, I'm actually not redirected to the same page in the other language.

#### Version Information
* WordPress: 4.9.7
* MultilingualPress: 2.11.1

#### Steps to Reproduce
1. Create more than one site each one with post related between them
2. Use Archive Widget on the sidebar of each site
3. Set up a menu to switch between the language sites created
4. Select one Archive from one of the site to get redirected to archive page
5. Now use menu to change language

#### What I Expected
To be redirected in the archive page for the selected language site

#### What Happened Instead
I am not redirected correctly

**Comment by Dinamiko** [comment]
This is already implemented in new MultilingualPress version 3.
