### ISSUE TITLE
Hreflang not adding to the HEAD

### ISSUE THREAD

**Issue by Jorgu5** [inpsyde/MultilingualPress#312]
#### Version Information
* WordPress: 4.9.7
* MultilingualPress: 2.11.1 

#### What I Expected

From what i'm aware of, Multilingualpress should add hreflang into the head automatically, after setting up proper language relations in the settings, which I did https://imgur.com/a/00ma7Nn but hreflangs are not added into the head at all.

I'm using a subfolder structure for WPMU. Anyone who had similar issue?

**Comment by widoz** [comment]
Hi @Jorgu5, 

I tested it but not able to replicate the issue. 
I correctly see `<link rel="alternate" hreflang="en-US" href="http://localhost/mlp2/"><link rel="alternate" hreflang="nl-NL" href="http://localhost/mlp2/italian/">` within the `head` tag of my site.

Could be a filter added by another plugin that remove our or you haven't `<?php wp_head(); ?>` in your `header.php` template file.

Can you use a default WordPress theme and deactivate all plugins to see if the issue persist?
If not, please enable again the theme and if the issue doesn't appear activate the plugins one by one to know which cause the issue.

Thank you

**Comment by Jorgu5** [comment]
Hey,

Thanks for response. I've activated now Twenty Seventeen theme and deactivated all the plugins besides ACF. Still no hreflang inside the head tag. I'm not sure what else could be the problem

**Comment by widoz** [comment]
I think we can try to debug a bit, if you are able to open and debug `wp-content/multilingualpress/src/inc/hreflang-header/Mlp_Hreflang_Header_Output.php` using xdebug or even with `var_dump` I wondering to know where the execution stop, so, can you add a `var_dump` after every `if` statement within `wp_head` method?

```
if ( is_paged() ) {
			return;
		}

var_dump('After is paged');

		$translations = $this->get_translations();
		if ( ! $translations ) {
			return;
		}

var_dump('After Translations');

		/**
		 * Filters if the hreflang links should be rendered.
		 *
		 * @since 2.8.0
		 *
		 * @param bool     $render       Whether or not hreflang links should be rendered.
		 * @param string[] $translations The available translations to be used for hreflang links.
		 */
		if ( ! apply_filters( 'multilingualpress.render_hreflang', count( $translations ) > 1, $translations ) ) {
			return;
		}

var_dump('After filter has been applied');
```

And tell me which text you see in the source code?

@Jorgu5

**Comment by Jorgu5** [comment]
Thanks for quick reply,

I see this one `string(14) "After is paged"` in the source code.

**Comment by widoz** [comment]
Thanks @Jorgu5 for the debugging.

This means you don't have any translations active.
May be you don't have any `published` post?

**Comment by widoz** [comment]
You have to create relations first and publish posts.

Try with even only one post, connect the english one to another and check that in both sites you see the hreflang.

**Comment by Dinamiko** [comment]
@Jorgu5 We are going to close the issue, feel free to reopen it or create a new one at any time, thanks.

**Comment by Jorgu5** [comment]
Yes, I have resolved it. 

I haven't set up relationships on each page manually https://i.imgur.com/u1I5SmP.jpg

Thanks for the help. All is working.
