### ISSUE TITLE
Make user biography field translatable

### ISSUE THREAD

**Issue by thefuxia** [inpsyde/MultilingualPress#95]
By default WordPress stores the content of the biography field in `wp-admin/profile.php` on each site all in the same value.

We could intercept the save operation and store the value in a field whose name includes the site ID. Then we do the same when that field is retrieved.

Additional tasks:
- include translated public user profiles in the HTTP redirect algorithm
- make it extendable to include more fields
- add an option to the MultilingualPress settings page to turn that feature off in case of plugin conflicts

**Comment by dnaber-de** [comment]
We should consider a solution for the UI which allows the user to manage all of her fields on one screen. Otherwise he has to move to each blog and on each blog to the profile page if he wants to change the description in all languages.

**Comment by dboune** [comment]
Hi everyone. I have to get this done for a client right away, with focus on the bio field. I see you have placed this in "Custom Plugin" / "Addon". I'll dig around in the code of course and figure out how to do this, but any pointers would be greatly appreciated. Thanks!!

**Comment by Dinamiko** [comment]
New features will be added in new version 3, we are going to provide support only for bugs in version 2.
